const dummyData = [
  {
    id: 1,
    title: "Product A",
    price: 19.99,
    date: new Date(2020, 7, 14),
    location: "canada",
  },
  {
    id: 2,
    title: "Product B",
    price: 29.99,
    date: new Date(2021, 2, 28),
    location: "at Work",
  },
  {
    id: 3,
    title: "Product C",
    price: 9.99,
    date: new Date(2020, 7, 14),
    location: "cicago",
  },
  {
    id: 4,
    title: "Product D",
    price: 39.99,
    date: new Date(2021, 5, 12),
    location: "not defined",
  },
  {
    id: 5,
    title: "Product A",
    price: 19.99,
    date: new Date(2021, 2, 28),
    location: "canada",
  },
  {
    id: 6,
    title: "Product B",
    price: 29.99,
    date: new Date(2021, 2, 28),
    location: "at Work",
  },
  {
    id: 7,
    title: "Product C",
    price: 9.99,
    date: new Date(2021, 2, 28),
    location: "cicago",
  },
  {
    id: 8,
    title: "Product D",
    price: 39.99,
    date: new Date(2020, 7, 14),
    location: "not defined",
  },
  {
    id: 9,
    title: "Product A",
    price: 19.99,
    date: new Date(2021, 5, 12),
    location: "canada",
  },
  {
    id: 10,
    title: "Product B",
    price: 29.99,
    date: new Date(2021, 5, 12),
    location: "at Work",
  },
  {
    id: 11,
    title: "Product C",
    price: 9.99,
    date: new Date(2021, 2, 28),
    location: "cicago",
  },
  {
    id: 12,
    title: "Product D",
    price: 39.99,
    date: new Date(2020, 7, 14),
    location: "not defined",
  },
];

export default dummyData;
