const dummyData = [
  {
    id: 1,
    title: "Product A",
    amount: 1999,
    date: new Date(2022, 7, 14),
    location: "Surat",
  },
  {
    id: 2,
    title: "Product B",
    amount: 2999,
    date: new Date(2021, 2, 28),
    location: "at Work",
  },
  {
    id: 3,
    title: "Product C",
    amount: 999,
    date: new Date(2020, 7, 14),
    location: "Amdavad",
  },
  {
    id: 4,
    title: "Product D",
    amount: 3999,
    date: new Date(2021, 5, 12),
    location: "Office",
  },
  {
    id: 5,
    title: "Product A",
    amount: 1999,
    date: new Date(2021, 2, 28),
    location: "Surat",
  },
  {
    id: 6,
    title: "Product B",
    amount: 2999,
    date: new Date(2021, 2, 28),
    location: "at Work",
  },
  {
    id: 7,
    title: "Product C",
    amount: 999,
    date: new Date(2021, 2, 28),
    location: "Amdavad",
  },
  {
    id: 8,
    title: "Product D",
    amount: 3999,
    date: new Date(2020, 7, 14),
    location: "Office",
  },
  {
    id: 9,
    title: "Product A",
    amount: 1999,
    date: new Date(2021, 5, 12),
    location: "Surat",
  },
  {
    id: 10,
    title: "Product B",
    amount: 2999,
    date: new Date(2021, 5, 12),
    location: "at Work",
  },
  {
    id: 11,
    title: "Product C",
    amount: 999,
    date: new Date(2021, 2, 28),
    location: "Amdavad",
  },
  {
    id: 12,
    title: "Product D",
    amount: 3999,
    date: new Date(2020, 7, 14),
    location: "Office",
  },
];

export default dummyData;
